config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:registrations]
  resources :users do
    collection do 
      get :show_profile
      get :edit_profile
      get 'edit_profile/password' => 'users#change_password', :as => :change_password
      patch 'edit_profile/password' => 'users#update'

      get 'edit_profile/delete/' => 'users#destroy_confirm', :as => :destroy_confirm
      patch 'edit_profile/delete/' => 'users#destroy_with_password', :as => :destroy
    end
    member do
      get 'edit/password' => 'users#change_users_password', :as => :change_users_password
      patch 'edit/password' => 'users#update'
      get 'edit/delete/' => 'users#destroy_confirm', :as => :destroy_user_confirm
      patch 'edit/delete/' => 'users#destroy_with_password', :as => :destroy_user
    end
  end

  resources :namespaces do
    collection do 
       
    end
    member do
    
    end
  end
  resources :projects do
    collection do 
      
    end
    member do

      resources :tasks, param: :task_id 
      
    end
  end

  root :to => "users#index"
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)      default(""), not null
#  surname                :string(255)      default(""), not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  admin                  :boolean
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # has_many :projects
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :tasks
end
# nested atributes_for

#  widok:
#  fields_for @users 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  before_filter do
    @user = User.find(current_user.id)
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Dodano użytkownika." 
      redirect_to root_path
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    unless current_user.id == @user.id 
      if current_user.admin? and @user.admin? then
       redirect_to root_path 
     end
    end
    
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Poprawnie edytowano użytkownika."
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Usunięto użytkownika."
      redirect_to root_path
    end
  end 

  def show_profile
    @user = User.find(current_user.id)
  end

  def edit_profile
    @user = User.find(current_user.id)
    render :action => 'edit'
  end

  def destroy_confirm
    if params[:id].present?
      @user = User.find(params[:id])
    end
  end

  def destroy_with_password
    if params[:id].present?
      @user = User.find(params[:id])
    end
    @user.errors[:base] << "Niepoprawne hasło" unless current_user.valid_password?(user_params[:password])

    if @user.errors.empty? and @user.destroy
      flash[:notice] = "Poprawnie usunięto użytkownika."
      redirect_to root_path

    else
      if params[:id].present?
        redirect_to destroy_user_confirm_user_path
      else
        redirect_to destroy_confirm_users_path
      end
    end
  end

  def change_password

  end

  def change_users_password
    @user = User.find(params[:id])
    render 'users/change_password'
  end

  protected

  def user_params
      params.require(:user).permit(:name, :surname, :email, :password, :password_confirmation, :admin,:commit)
  end


  

end

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.input :name, required: true, autofocus: true, label: 'Imię'
  = f.input :surname, required: true, label: 'Nazwisko' 
  = f.input :email, required: true, label: 'Adres E-mail' 
  = f.input :password, label: 'Hasło', hint: ("Minimum #{@minimum_password_length} znaków" if @validatable) 
  = f.input :password_confirmation,  label: 'Powtórz Hasło' 
  =f.input :current_password, label: 'Hasło administratora' ,hint: "Podaj swoje hasło, aby potwierdzić zmiany", required: true
  = f.input :admin 
  = f.submit

app/views/users/_new.html.erb
<%= simple_form_for @user do |f| %>
 <%= f.error_notification %> 

  <div class="form-inputs">
    <%= f.input :name, required: true, autofocus: true, label: 'Imię' %>
    <%= f.input :surname, required: true, label: 'Nazwisko' %>
    <%= f.input :email, required: true, label: 'Adres E-mail' %>
    <% if current_user.admin? && @user.id != current_user.id %>
      <%= f.input :admin, label: 'Czy admin' %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Zapisz" %>
    <span class="or">lub</span>
    <% if params[:id].present? %>
      <%= link_to "Wróć", users_path, :class => "btn btn-default" %>
      <% else %>
      <%= link_to "Wróć", show_profile_users_path, :class => "btn btn-default" %>
    <% end %>
  </div>
<% end %>

app/views/users/_new_password.html.erb
<%= simple_form_for @user do |f| %>
 <%= f.error_notification %> 
  <div class="form-inputs">
    <%= f.input :password, required: true, label: 'Nowe Hasło', hint: ("Minimum #{@minimum_password_length} znaków" if @validatable) %>
    <%= f.input :password_confirmation, required: true, label: 'Powtórz Hasło' %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Zapisz" %>
  </div>
<% end %>

<% if params[:id].present? %>
  <%= link_to "Powrót", edit_user_path(params[:id]), :class => "btn btn-primary"%>
  <% else %>
  <%= link_to "Powrót", show_profile_users_path, :class => "btn btn-primary"%>
<% end %>

app/views/users/_password_confirm.html.slim
=simple_form_for @user, url: abc do |f|
	f.error_notification
	  .form-inputs
	  	=f.input :password, required: true, label: 'Hasło'
	  .form-actions
	    =f.button :submit, "Potwierdź"
-if params[:id].present?
	= link_to "Powrót", users_path, :class => "btn btn-primary"

app/views/users/_tr.html.slim
tr
  td = user.name 
  td = user.surname 
  td = user.email
  td  
    -if (user.admin?)
      span.glyphicon.glyphicon-ok
    -else
      span.glyphicon.glyphicon-remove
  -if can? :create, :user 
  	td =link_to "Usuń", destroy_user_confirm_user_path(user), class: "btn btn-danger"
  	td = link_to 'Edytuj', edit_user_path(user), class: "btn btn-warning"
  -else
    td[colspan = 2]
  

app/views/users/change_password.html.slim
h1.page-header Zmiana hasła

=render "users/new_password"

app/views/users/destroy_confirm.html.slim
h1.page-header Usuwanie konta

-if @user.admin?
	p Usunięcie konta spowoduje usunięcie wszystkich namespace'ów oraz projektów, które stworzyłeś! TEJ OPERACJI NIE MOŻNA COFNĄĆ!
	p Aby potwierdzić, wpisz swoje hasło:
-else
	p Usunięcie konta spowoduje usunięcie użytkownika ze wszystkich projektów, w których brał on udział. TEJ OPERACJI NIE MOŻNA COFNĄĆ!
	p Aby potwierdzić, wpisz swoje hasło:
-if params[:id].present?
	=render partial: '/users/password_confirm', locals: { abc: destroy_user_user_path(params[:id]) }
-else
	=render partial:'/users/password_confirm', locals: { abc: destroy_users_path} 

app/views/users/edit.html.slim
h1.page-header Edycja użytkownika

-if params[:id].present?
	=link_to "Zmiana hasła",change_users_password_user_path , :class => 'btn btn-primary'
-else
	=link_to "Zmiana hasła",change_password_users_path , :class => 'btn btn-primary'

=render "users/new"

app/views/users/index.html.slim
  h1.page-header Dashboard
  div class=("alert alert-success" if flash[:notice]) role="alert" =flash[:notice]
  table#users.table.table-striped
    thead
      tr
        th Imie
        th Nazwisko
        th E-mail
        th Admin
        -if can? :create, :user
          th Usuń
          th Edytuj          
    tbody
      -if can? :create, :user
        =link_to 'Nowy użytkownik', new_user_path, class: "btn btn-primary "
      -@users.each do |user| 
        = render :partial => "tr", locals: {user: user}

app/views/users/new.html.erb
<h1 class="page-header">Dodaj nowego użytkownika</h1>

<%= simple_form_for @user do |f| %>
<!--   <%= f.error_notification %> -->

  <div class="form-inputs">
    <%= f.input :name, required: true, autofocus: true, label: 'Imię' %>
    <%= f.input :surname, required: true, label: 'Nazwisko' %>
    <%= f.input :email, required: true, label: 'Adres E-mail' %>
    <%= f.input :password, required: true, label: 'Hasło', hint: ("Minimum #{@minimum_password_length} znaków" if @validatable) %>
    <%= f.input :password_confirmation, required: true, label: 'Powtórz Hasło' %>
    <%= f.input :admin, label: 'Czy admin' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Rejestruj" %>
  </div>
<% end %>

app/views/users/show.html.slim
  p.notice
  h1.page-header Lista uzytkownikow
  table#users.table.table-striped
    thead
      tr
        th Imie
        th Nazwisko
        th E-mail
        th Admin
        -if can? :create, :user
          th Usuń
          th Edytuj          
    tbody
      -if can? :create, :user
        =link_to 'Nowy użytkownik', new_user_path, class: "btn btn-primary "
      -@users.each do |user| 
        = render :partial => "tr", locals: {user: user}

app/views/users/show_profil.html.slim
p.notice
  h1.page-header Dane profilu
  table#users.table.table-striped
    thead
      tr
        td Imie
        td[colspan = 2] =@user.name
      tr
        td Nazwisko
        td[colspan = 2] =@user.surname
      tr
        td E-mail
        td[colspan = 2] =@user.email
      tr
        td Uprawnienia
        td =@user.admin
      td = link_to 'Edytuj', edit_user_path, class: "btn btn-warning"
      td = link_to "Usuń", admin_destroy_user_path, method: :delete, data: { confirm: "Czy na pewno chcesz usunąć użytkownika" }, class: "btn btn-danger"
      td = link_to 'Powrót',:back, class: "btn btn-primary "
  / td =link_to "Usuń", admin_destroy_user_path(user), method: :delete, data: { confirm: "Czy na pewno chcesz usunąć użytkownika" }, class: "btn btn-danger"
  / td = link_to 'Edytuj', edit_user_path(user), class: "btn btn-warning"
      
      

      
      

    

app/views/users/show_profile.html.slim
p.notice
  h1.page-header Dane profilu
  table#users.table.table-striped
    thead
      tr
        td Imie
        td[colspan = 2] =@user.name
      tr
        td Nazwisko
        td[colspan = 2] =@user.surname
      tr
        td E-mail
        td[colspan = 2] =@user.email
      tr
        td Uprawnienia
        td =@user.admin
      td = link_to 'Edytuj', edit_profile_users_path, class: "btn btn-warning"
      td = link_to "Usuń", destroy_confirm_users_path, class: "btn btn-danger"
      td = link_to 'Powrót',:back, class: "btn btn-primary "
  / td =link_to "Usuń", admin_destroy_user_path(user), method: :delete, data: { confirm: "Czy na pewno chcesz usunąć użytkownika" }, class: "btn btn-danger"
  / td = link_to 'Edytuj', edit_user_path(user), class: "btn btn-warning"
      
      

      
      

    