config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:registrations]
  resources :users do
    collection do 
      get :show_profile
      get :edit_profile
      get 'edit_profile/password' => 'users#change_password', :as => :change_password
      patch 'edit_profile/password' => 'users#update'

      get 'edit_profile/delete/' => 'users#destroy_confirm', :as => :destroy_confirm
      patch 'edit_profile/delete/' => 'users#destroy_with_password', :as => :destroy
    end
    member do
      get 'edit/password' => 'users#change_users_password', :as => :change_users_password
      patch 'edit/password' => 'users#update'
      get 'edit/delete/' => 'users#destroy_confirm', :as => :destroy_user_confirm
      patch 'edit/delete/' => 'users#destroy_with_password', :as => :destroy_user
    end
  end

  resources :namespaces do
    collection do 
       
    end
    member do
    
    end
  end
  resources :projects do
    collection do 
      
    end
    member do

      resources :tasks, param: :task_id 
      
    end
  end

  root :to => "users#index"
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  date_begin   :date
#  date_end     :date
#  description  :text(65535)
#  status       :boolean
#  user_id      :integer
#  namespace_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Project < ActiveRecord::Base
	# belongs_to :user
	has_and_belongs_to_many :users
	has_many :tasks
	belongs_to :namespaces
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  def index
    @project = Project.all
    # @project =Project.find(params[:namespace_id]) tutaj zeby wyyswietlalo namespace z tabeli laczacej


  end

  def new
    @project = Project.new
    set_default_data
    
  end

  def create
    @project = Project.new(project_params)
    # @user = User.find(params[24])
    # @user.projects << @projects
    
    # respond_to do |format|
    #   format.js
    # end
      #if @project.save
        # flash[:notice] = "Namespace został utworzony."
      #  redirect_to projects_path
     # end
      respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Projekt został poprawnie dodany' }
        format.json { render :show, status: :ok, location: @project }

      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        red
      end
    end
    #   else
    #     flash[:error] = "Namespace nie został utworzony."
    #     format.html { render :new }
    #   end
    # end
  end

  def show
  respond_to do |format|
  format.html # show.html.erb
  format.xml { render :xml => @project.to_xml }
  end
  end

  def edit

  end

  def update
    
     respond_to do |format|
      if @project.update(project_params)
        #format.html { redirect_to projects_path, notice: 'Projekt został poprawnie zaktualizowany' }
        #format.json { render :show, status: :ok, location: @project }
        flash[:notice] = "Projekt został poprawnie zaktualizowany"
        format.html { redirect_to projects_path }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        red
      end
    end

  end

  def destroy
    @project.destroy
    respond_to do |format|
      if @project.destroy
        format.html { redirect_to projects_path, notice: 'Projekt został usuniety' }
        format.json { render :show, status: :ok, location: @project }

      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        red
      end
    end
    
  end 

  def set_default_data
    @project.date_begin = DateTime.now
    @project.status = true
  end

  def project_params
    params.require(:project).permit(:name,:date_begin,:date_end,:description,:status,:namespace_id,:user_ids =>[])
  end
end

app/views/projects/_form.html.slim
= simple_form_for @project do |f| 
	= f.error_notification 
	.form-inputs
  	= f.input :name, required: true, :autofocus => true, :as => :string , label: 'Nazwa'
    = f.input  :date_begin, required: true, as: :date_picker,  label: 'Data rozpoczęcia',input_html: { class: 'date' } 
    = f.input :date_end, required: true, label: 'Data zakończenia',as: :date_picker
    = f.input :description, label: 'Opis'
    = f.input :status,  autofocus: true, label: 'Rozpoczęty'
    / = f.input :name, :label => "Namespace", :as => :select, collection: @namespaces,  :input_html => {:id => "e1"}
    / = f.simple_fields_for :namespaces do |p|
    /   = p.input :namespace, :as => :select , collection: Namespace.all
    / end
    /f assocaction
    = f.input :namespace_id, :as => :select, collection: Namespace.all
    = f.association :users, :as => :check_boxes, collection: User.all
	form-actions
  	= f.button :submit, "Zapisz"
    span.or lub
    = link_to "Wróć", :back, :class => "btn btn-default"
/ javascript:
/   var project = new Project;
/   project.date();

app/views/projects/_tr.html.slim
tr
  td = project.name 
  td = project.date_begin 
  td = project.date_end
  td = project.description
  td 
    -if (project.status?)
      span.glyphicon.glyphicon-ok
    -else
      span.glyphicon.glyphicon-remove
  td = project.namespace_id
  td = link_to "Zadania", tasks_path(project), class: "btn btn-info"
  -if can? :create, :user 
  	td =link_to "Usuń", project_path(project), class: "btn btn-danger", method: :delete, data:{confirm: "Czy jesteś pewien?"}
  	td = link_to 'Edytuj', edit_project_path(project), class: "btn btn-warning"
  -else
    td[colspan = 2]

    destroy_user_confirm_user_path(user)

app/views/projects/edit.html.slim
=render "projects/form"

app/views/projects/index.html.slim
h1.page-header Projekty
div class=("alert alert-success" if flash[:notice]) role="alert" =flash[:notice]
-if can? :create, :user
	=link_to 'Nowy projekt', new_project_path, class: "btn btn-primary "
table#users.table.table-striped
	thead
		tr
			th Nazwa
			th Data rozpoczęcia
			th Data zakończenia
			th Opis
			th Status
			th Namespace
			th Zadania
			-if can? :create, :user 
				th Usuń
				th Edytuj
	tbody 
	  -@projects.each do |project| 
	    = render :partial => "tr", locals: {project: project}

app/views/projects/new.html.slim
h1.page-header Dodaj nowy projekt
=render "projects/form"
/ =render ""