config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:registrations]
  resources :users do
    collection do 
      get :show_profile
      get :edit_profile
      get 'edit_profile/password' => 'users#change_password', :as => :change_password
      patch 'edit_profile/password' => 'users#update'

      get 'edit_profile/delete/' => 'users#destroy_confirm', :as => :destroy_confirm
      patch 'edit_profile/delete/' => 'users#destroy_with_password', :as => :destroy
    end
    member do
      get 'edit/password' => 'users#change_users_password', :as => :change_users_password
      patch 'edit/password' => 'users#update'
      get 'edit/delete/' => 'users#destroy_confirm', :as => :destroy_user_confirm
      patch 'edit/delete/' => 'users#destroy_with_password', :as => :destroy_user
    end
  end

  resources :namespaces do
    collection do 
       
    end
    member do
    
    end
  end
  resources :projects do
    collection do 
      
    end
    member do

      resources :tasks, param: :task_id 
      
    end
  end

  root :to => "users#index"
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/views/layouts/_menu.html.slim
.col-sm-3.col-md-2.sidebar
  ul.nav.nav-sidebar
    li class=('active' if params[:controller] == 'users') =link_to "Dashboard", users_path
    li class=('active' if params[:controller] == 'namespaces') =link_to "Namespace'y", namespaces_path
    li class=('active' if params[:controller] == 'projects') =link_to "Projekty", projects_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trollo</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Trollo", root_path, :class => 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
          <% if can? :update, current_user %>
          <%= link_to "Profil", show_profile_users_path, :class => 'navbar-link' %> </li>
          <% end %>
          <li><%= link_to "Wyloguj", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <% else %>
         <li> <%= link_to "Zaloguj", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <div class="row">
    <% if user_signed_in? %>
    <%= render "layouts/menu" %>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <% else %>
    <div class="col-sm-12">
    <% end %>
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>